name: CI - Build and Test SwaggerProj

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0  # .NET SDK with correct dependencies

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore Swagger.Tests.sln
      working-directory: ./SwaggerProj/Swagger.Tests

    - name: Build the solution
      run: dotnet build Swagger.Tests.sln --no-restore --configuration Release
      working-directory: ./SwaggerProj/Swagger.Tests

    - name: Run tests
      run: dotnet test Swagger.Tests.sln --no-build --verbosity normal --configuration Release
      working-directory: ./SwaggerProj/Swagger.Tests
