name: CI - Build and Test SwaggerProj

on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Run tests'
        required: false
        default: 'Test running'

  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: lijon1990/swaggerproj:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore Swagger.Tests.sln
      working-directory: ./SwaggerProj/Swagger.Tests

    - name: Build the solution
      run: dotnet build Swagger.Tests.sln --no-restore --configuration Release
      working-directory: ./SwaggerProj/Swagger.Tests

    - name: Run tests
      run: dotnet test Swagger.Tests.sln --no-build --verbosity normal --configuration Release
      working-directory: ./SwaggerProj/Swagger.Tests

