name: Rnn tests on CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install libssl1.1 (for .NET compatibility)
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1 || sudo apt-get install -y libssl1.0.0 || true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore
