name: Rnn tests on CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./SwaggerProj/Swagger.Tests

    - name: Build the solution
      run: dotnet build --no-restore
      working-directory: ./SwaggerProj/Swagger.Tests

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./SwaggerProj/Swagger.Tests