name: Workflow 1 - List Changed Files

on:
  push:
    branches:
      - feature/workflow-file-changes-trigger  # or your default branch

jobs:
  list_changed_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files changed since last commit
        run: |
          echo "Changed files:"
          git diff --name-only HEAD~1 HEAD
